# Generated by Django 3.2.23 on 2024-10-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notifications', '0010_alter_gcmdevice_options_and_more'),
        ('push_notifications', '0010_auto_20230705_0813'),
    ]

    operations = [
    ]

